# Generated by Django 3.0.5 on 2020-04-20 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word_translation", models.CharField(max_length=150)),
                ("word_to_learn", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("word_image", models.ImageField(blank=True, upload_to="Word_Images")),
                ("word_status", models.IntegerField(default=1)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users_word",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
